### ISSUE TITLE
网络

### ISSUE THREAD

**Issue by ctykwz** [xidian-rs/Ruisi#15]
这次是不打算开了吗

**Comment by KingsFish** [comment]
睿思服务器出现了一点问题，外网域名暂时不可用。不过很快会修好，请耐心等待。

**Comment by KingsFish** [comment]
这个是硬件问题，很快会修复，非常感谢。

不过睿思技术后台正在招募，可以去 [永久招募公告](http://rs.xidian.edu.cn/forum.php?mod=viewthread&tid=943815) 申请一下

**Comment by ctykwz** [comment]
等恢复了，打不开链接

**Comment by darkgirl** [comment]
现在还没恢复么?好像都一个多月了, 如果恢复了,求个邮件提示,谢谢学姐们(学长们)

**Comment by freedom10086** [comment]
> 现在还没恢复么?好像都一个多月了, 如果恢复了,求个邮件提示,谢谢学姐们(学长们)

**Comment by freedom10086** [comment]
是的还没好。。。

**Comment by ctykwz** [comment]
时间有点长诶，估计现在都在备考吧.

**Comment by KingsFish** [comment]
> 时间有点长诶，估计现在都在备考吧.

硬件故障已经修复了，剩下的需要进行软件配置，比如数据迁移等，另外还需要学校配合弄外网域名的事情，快了。

**Comment by ctykwz** [comment]
坏的有点彻底啊

**Comment by darkgirl** [comment]
学长学姐加油啊

**Comment by darkgirl** [comment]
还没考完试么, 还是说都回家啦

**Comment by zhangtianle** [comment]
修复完后会更换外网域名吗

**Comment by darkgirl** [comment]
依然无法访问?

**Comment by darkgirl** [comment]
老哥们, 我居然看到睿思404, 是不是说明希望还没破灭?

**Comment by ctykwz** [comment]
一个季度了

**Comment by darkgirl** [comment]
挖坟挖坟

**Comment by KingsFish** [comment]
外网已恢复，各位可以愉快玩耍了

**Comment by darkgirl** [comment]
> 外网已恢复，各位可以愉快玩耍了

多谢多谢,

**Comment by ctykwz** [comment]
稳   时隔这么久了  还以为彻底废了

KSha <notifications@github.com> 于2019年3月24日周日 下午4:00写道：
