### ISSUE TITLE
外网异常

### ISSUE THREAD

**Issue by dayAndnight2018** [xidian-rs/Ruisi#17]
2019.6.3外网访问异常，找工作关键时间点，请及时修复外网访问，谢谢！

**Comment by darkgirl** [comment]
额............睿思正在修复...外网能看到电脑版的'bug?' 已经花了4, 5天了

**Comment by KingsFish** [comment]
接学校通知，睿思手机版的校外访问至少在本月12号之后才能恢复，请大家耐心等待

**Comment by darkgirl** [comment]
> 接学校通知，睿思手机版的校外访问至少在本月12号之后才能恢复，请大家耐心等待

这么长时间, 不是只是调试个bug吗.?.....为什么是学校通知的?

**Comment by dayAndnight2018** [comment]
> 额............睿思正在修复...外网能看到电脑版的'bug?' 已经花了4, 5天了

啥bug得修复四五天

**Comment by ctykwz** [comment]
应该是因为五三五30周年吧
