### ISSUE TITLE
睿思继续失联, issue继续提

### ISSUE THREAD

**Issue by darkgirl** [xidian-rs/Ruisi#18]
提到重连为止

**Comment by ctykwz** [comment]
hk一出事，估计又是停半个月

**Comment by johnowner** [comment]
什么时候能恢复访问

**Comment by JuiYang** [comment]
不停闪退，差点被系统检测为恶意软件

**Comment by freedom10086** [comment]
> 不停闪退，差点被系统检测为恶意软件

什么手机 系统版本多少 什么网路环境？

**Comment by darkgirl** [comment]
这是什么情况


> > 不停闪退，差点被系统检测为恶意软件
> 
> 什么手机 系统版本多少 什么网路环境？

![捕获](https://user-images.githubusercontent.com/28688741/59776138-e42f1380-92e4-11e9-9434-d08f4fe4b341.PNG)

**Comment by dayAndnight2018** [comment]
> 这是什么情况
> 
> > > 不停闪退，差点被系统检测为恶意软件
> > 
> > 
> > 什么手机 系统版本多少 什么网路环境？
> 
> ![捕获](https://user-images.githubusercontent.com/28688741/59776138-e42f1380-92e4-11e9-9434-d08f4fe4b341.PNG)

哟！这问题可不简单哦！系统维护就直接把Down掉吧

**Comment by JuiYang** [comment]
可能是系统在维护吧，最近访问就很正常

**Comment by JuiYang** [comment]
> > 不停闪退，差点被系统检测为恶意软件
> 
> 什么手机 系统版本多少 什么网路环境？

可能是系统在维护吧，最近手机没有出现这个问题

**Comment by JuiYang** [comment]
> > 这是什么情况
> > > > 不停闪退，差点被系统检测为恶意软件
> > > 
> > > 
> > > 什么手机 系统版本多少 什么网路环境？
> > 
> > 
> > ![捕获](https://user-images.githubusercontent.com/28688741/59776138-e42f1380-92e4-11e9-9434-d08f4fe4b341.PNG)
> 
> 哟！这问题可不简单哦！系统维护就直接把Down掉吧

你这种情况是不是在外网访问阿

**Comment by JuiYang** [comment]
> 这是什么情况
> 
> > > 不停闪退，差点被系统检测为恶意软件
> > 
> > 
> > 什么手机 系统版本多少 什么网路环境？
> 
> ![捕获](https://user-images.githubusercontent.com/28688741/59776138-e42f1380-92e4-11e9-9434-d08f4fe4b341.PNG)

你这种情况是不是在外网访问阿

**Comment by darkgirl** [comment]
> > 这是什么情况
> > > > 不停闪退，差点被系统检测为恶意软件
> > > 
> > > 
> > > 什么手机 系统版本多少 什么网路环境？
> > 
> > 
> > ![捕获](https://user-images.githubusercontent.com/28688741/59776138-e42f1380-92e4-11e9-9434-d08f4fe4b341.PNG)
> 
> 你这种情况是不是在外网访问阿

对滴, 外网啥时候才能用呀

**Comment by dayAndnight2018** [comment]
这次什么时候恢复啊？

**Comment by freedom10086** [comment]
> 这次什么时候恢复啊？

具体我也不清楚，我也只是开发

**Comment by darkgirl** [comment]
很有可能是永别

**Comment by dayAndnight2018** [comment]
> 很有可能是永别

外网已经修复了啊

**Comment by ShonveSue** [comment]
安卓客户端是不是用不了呀？刷新不出来消息，而且登录的时候验证码不显示。
