### ISSUE TITLE
校外网睿思访问

### ISSUE THREAD

**Issue by luwanglin** [xidian-rs/Ruisi#26]
这几天校外无法访问睿思了，提一下问题

**Comment by KingsFish** [comment]
![4a2eb2b70ab97a8f](https://user-images.githubusercontent.com/12454995/84616917-f0ea4580-aeff-11ea-8439-16a87c996ce5.png)

**Comment by Lynch201** [comment]
是啥问题啊，我也是做相关技术的，是否需要提供帮助？

**Comment by 756556166** [comment]
对啊，需要啥帮助不？这两天在校外的同学正需要睿思看就业信息啥的，这一挂影响太大了

**Comment by KingsFish** [comment]
感谢提供帮助，不过这次是非技术原因，请耐心等候维护结束
